### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by ATakaSKY** [Enngage/ngx-paypal#1] opened 2018-03-14 03:09 UTC
The application on compilation throws below error:

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-paypal/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

Any idea why?

**Comment by Enngage** [comment] 2018-03-14 06:48
This seems to be a problem with angular as discussed [here ](https://github.com/angular/angular/issues/21670)and [here](https://github.com/angular/angular/issues/21925). 

Some people also suggested removing node_modules and installing the modules from scratch so I would recommend to try that. There isn't anything really fancy in this module so I don't suppose its caused by code in here. For a sample application, check this [demo](https://github.com/Enngage/ngx-paypal/tree/master/src/demo).

**Comment by Enngage** [comment] 2018-03-14 11:40
Seems like this might have been caused by my code afterall. At least I experienced issues (different that you posted though) during AOT compilation. I've refactored the application a bit and it should be ok now. At least my other private app is working as expected in latest Angular 5 & AOT build

**Comment by Enngage** [comment] 2018-03-20 11:09
Closing as this should no longer be an issue

**Closed by Enngage** 2018-03-20 11:09 UTC
